import type {
  Vessel,
  Project,
  WorkPackage,
  InspectionEvent,
  DefectRecord,
  ChangeOrder,
  OwnerApproval,
  Document,
  ProjectMember,
  WorldModelEvent,
  AuthUser,
} from './types'

// ─── Vessel ───────────────────────────────────────────────────────────────────

export const MOCK_VESSEL: Vessel = {
  id: 'vessel-001',
  name: 'Project ZERO',
  hull_id: 'PZ-55K-2008',
  vessel_type: 'Sailing Yacht Ketch',
  loa: 55.0,
  beam: 10.2,
  draft: 4.8,
  gross_tonnage: 498,
  flag_state: 'Cayman Islands',
  class_society: 'RINA',
  class_number: 'RINA-2008-4491',
  year_built: 2008,
  build_yard: 'Perini Navi',
  created_at: '2026-01-01T00:00:00Z',
}

// ─── Project ──────────────────────────────────────────────────────────────────

export const MOCK_PROJECT: Project = {
  id: 'project-001',
  vessel_id: 'vessel-001',
  name: 'Project ZERO — 5 Year Survey 2026',
  project_type: 'FIVE_YEAR_SURVEY',
  phase: 'PRE_SURVEY',
  yard_name: 'Pendennis Shipyard',
  yard_location: 'Falmouth, UK',
  planned_start: '2026-05-01',
  planned_delivery: '2026-08-15',
  actual_start: null,
  actual_delivery: null,
  budget_locked: 1850000,
  budget_spent: 24500,
  budget_contingency: 185000,
  class_society: 'RINA',
  survey_due_date: '2026-06-30',
  created_at: '2026-01-15T00:00:00Z',
  vessel: MOCK_VESSEL,
}

// ─── Work Packages ────────────────────────────────────────────────────────────

export const MOCK_WORK_PACKAGES: WorkPackage[] = [
  {
    id: 'wp-001',
    project_id: 'project-001',
    wp_number: 'WP-CLASS-001',
    title: 'Hull Class Survey — Steel & Framing',
    discipline: 'CLASS',
    description: 'Full hull structural survey per RINA 5-year requirements including ultrasonic thickness measurements on all steel plating and frames.',
    status: 'SCOPED',
    planned_hours: 240,
    actual_hours: 0,
    planned_cost: 48000,
    actual_cost: 0,
    trade_contractor: 'RINA Surveyor',
    planned_start: '2026-05-05',
    planned_end: '2026-05-20',
    actual_start: null,
    actual_end: null,
    is_class_item: true,
    class_society: 'RINA',
    class_item_ref: 'RINA-HS-001',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-002',
    project_id: 'project-001',
    wp_number: 'WP-HULL-001',
    title: 'Hull Blasting & Anti-Fouling',
    discipline: 'HULL',
    description: 'Full hull blasting to Sa 2.5, epoxy prime coat, and application of premium anti-fouling system.',
    status: 'SCOPED',
    planned_hours: 480,
    actual_hours: 0,
    planned_cost: 85000,
    actual_cost: 0,
    trade_contractor: 'Pendennis Coatings',
    planned_start: '2026-05-15',
    planned_end: '2026-06-10',
    actual_start: null,
    actual_end: null,
    is_class_item: false,
    class_society: null,
    class_item_ref: null,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-003',
    project_id: 'project-001',
    wp_number: 'WP-MECH-001',
    title: 'Main Engine Service — Port & Starboard',
    discipline: 'MECHANICAL',
    description: 'Full 5,000-hour service on both Caterpillar C18 main engines including injector replacement, heat exchanger overhaul, and alignment check.',
    status: 'ACTIVE',
    planned_hours: 320,
    actual_hours: 45,
    planned_cost: 62000,
    actual_cost: 8500,
    trade_contractor: 'Finning CAT',
    planned_start: '2026-04-20',
    planned_end: '2026-05-30',
    actual_start: '2026-04-22',
    actual_end: null,
    is_class_item: true,
    class_society: 'RINA',
    class_item_ref: 'RINA-ME-002',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-004',
    project_id: 'project-001',
    wp_number: 'WP-ELEC-001',
    title: 'Electrical Systems Survey & Upgrade',
    discipline: 'ELECTRICAL',
    description: 'Full electrical survey per RINA requirements. Upgrade shore power system to 100A/480V three-phase. Replace aging wiring runs in engine room.',
    status: 'SCOPED',
    planned_hours: 280,
    actual_hours: 0,
    planned_cost: 54000,
    actual_cost: 0,
    trade_contractor: 'Pendennis Electrical',
    planned_start: '2026-05-20',
    planned_end: '2026-06-25',
    actual_start: null,
    actual_end: null,
    is_class_item: true,
    class_society: 'RINA',
    class_item_ref: 'RINA-EL-003',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-005',
    project_id: 'project-001',
    wp_number: 'WP-RIG-001',
    title: 'Standing Rigging Replacement',
    discipline: 'RIGGING',
    description: 'Full replacement of all standing rigging including main mast shrouds, forestay, backstays, and all associated terminals. Seldén supplied.',
    status: 'ACTIVE',
    planned_hours: 160,
    actual_hours: 12,
    planned_cost: 38500,
    actual_cost: 2400,
    trade_contractor: 'Pendennis Rigging',
    planned_start: '2026-04-25',
    planned_end: '2026-05-25',
    actual_start: '2026-04-28',
    actual_end: null,
    is_class_item: false,
    class_society: null,
    class_item_ref: null,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-006',
    project_id: 'project-001',
    wp_number: 'WP-PAINT-001',
    title: 'Topsides & Superstructure Repaint',
    discipline: 'PAINT',
    description: 'Full fairing and repaint of topsides and superstructure in original Perini white. Awlgrip HDT system.',
    status: 'DRAFT',
    planned_hours: 600,
    actual_hours: 0,
    planned_cost: 110000,
    actual_cost: 0,
    trade_contractor: null,
    planned_start: '2026-06-15',
    planned_end: '2026-07-20',
    actual_start: null,
    actual_end: null,
    is_class_item: false,
    class_society: null,
    class_item_ref: null,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-007',
    project_id: 'project-001',
    wp_number: 'WP-INT-001',
    title: 'Interior Soft Furnishings Refresh',
    discipline: 'INTERIOR',
    description: 'Replace all saloon upholstery, master cabin soft furnishings, and guest cabin bedding. New carpet in passageways.',
    status: 'DRAFT',
    planned_hours: 200,
    actual_hours: 0,
    planned_cost: 42000,
    actual_cost: 0,
    trade_contractor: null,
    planned_start: '2026-07-01',
    planned_end: '2026-07-30',
    actual_start: null,
    actual_end: null,
    is_class_item: false,
    class_society: null,
    class_item_ref: null,
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-008',
    project_id: 'project-001',
    wp_number: 'WP-SAFE-001',
    title: 'Safety Equipment Survey & Renewal',
    discipline: 'SAFETY',
    description: 'Full survey and renewal of all SOLAS safety equipment. Life rafts, EPIRBs, flares, fire extinguishers.',
    status: 'SCOPED',
    planned_hours: 80,
    actual_hours: 0,
    planned_cost: 18500,
    actual_cost: 0,
    trade_contractor: 'Ocean Safety',
    planned_start: '2026-05-25',
    planned_end: '2026-06-05',
    actual_start: null,
    actual_end: null,
    is_class_item: true,
    class_society: 'RINA',
    class_item_ref: 'RINA-SF-004',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-009',
    project_id: 'project-001',
    wp_number: 'WP-STRUCT-001',
    title: 'Structural Weld Inspection & Repairs',
    discipline: 'STRUCTURAL',
    description: 'MPI inspection of all structural welds per RINA requirements. Remediation of any identified cracks or corrosion.',
    status: 'ON_HOLD',
    planned_hours: 120,
    actual_hours: 8,
    planned_cost: 22000,
    actual_cost: 1200,
    trade_contractor: 'Pendennis Structural',
    planned_start: '2026-05-10',
    planned_end: '2026-05-22',
    actual_start: '2026-04-30',
    actual_end: null,
    is_class_item: true,
    class_society: 'RINA',
    class_item_ref: 'RINA-ST-005',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'wp-010',
    project_id: 'project-001',
    wp_number: 'WP-MECH-002',
    title: 'Hydraulic Deck Equipment Overhaul',
    discipline: 'MECHANICAL',
    description: 'Overhaul of all hydraulic systems including anchor windlass, sail drives, and stabiliser rams.',
    status: 'SCOPED',
    planned_hours: 180,
    actual_hours: 0,
    planned_cost: 34000,
    actual_cost: 0,
    trade_contractor: 'Hydraulic Solutions Ltd',
    planned_start: '2026-06-01',
    planned_end: '2026-06-20',
    actual_start: null,
    actual_end: null,
    is_class_item: false,
    class_society: null,
    class_item_ref: null,
    created_at: '2026-01-20T00:00:00Z',
  },
]

// ─── Inspection Events ────────────────────────────────────────────────────────

export const MOCK_INSPECTIONS: InspectionEvent[] = [
  {
    id: 'insp-001',
    project_id: 'project-001',
    work_package_id: 'wp-001',
    inspection_number: 'INSP-CLASS-001',
    title: 'Initial Hull Condition Survey',
    inspector_role: 'CLASS_SURVEYOR',
    inspector_name: 'Marco Ferretti (RINA)',
    scheduled_date: '2026-05-06',
    actual_date: null,
    result: 'PENDING',
    notes: null,
    is_class_inspection: true,
    class_item_ref: 'RINA-HS-001',
    defect_count: 0,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'insp-002',
    project_id: 'project-001',
    work_package_id: 'wp-003',
    inspection_number: 'INSP-MECH-001',
    title: 'Engine Room Pre-Service Inspection',
    inspector_role: 'OWNERS_REP',
    inspector_name: 'Nadir (YAM.Limited)',
    scheduled_date: '2026-04-23',
    actual_date: null,
    result: 'PENDING',
    notes: null,
    is_class_inspection: false,
    class_item_ref: null,
    defect_count: 1,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'insp-003',
    project_id: 'project-001',
    work_package_id: 'wp-005',
    inspection_number: 'INSP-RIG-001',
    title: 'Standing Rigging Condition Assessment',
    inspector_role: 'YARD_QC',
    inspector_name: 'Tom Bradley (Pendennis)',
    scheduled_date: '2026-04-29',
    actual_date: null,
    result: 'PENDING',
    notes: null,
    is_class_inspection: false,
    class_item_ref: null,
    defect_count: 1,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'insp-004',
    project_id: 'project-001',
    work_package_id: 'wp-009',
    inspection_number: 'INSP-STRUCT-001',
    title: 'MPI Weld Survey — Engine Room Frames',
    inspector_role: 'CLASS_SURVEYOR',
    inspector_name: 'Marco Ferretti (RINA)',
    scheduled_date: '2026-05-12',
    actual_date: null,
    result: 'PENDING',
    notes: null,
    is_class_inspection: true,
    class_item_ref: 'RINA-ST-005',
    defect_count: 0,
    created_at: '2026-02-01T00:00:00Z',
  },
]

// ─── Defect Records ───────────────────────────────────────────────────────────

export const MOCK_DEFECTS: DefectRecord[] = [
  {
    id: 'defect-001',
    project_id: 'project-001',
    inspection_event_id: 'insp-002',
    work_package_id: 'wp-003',
    ncr_number: 'NCR-2026-001',
    title: 'Starboard Engine Seawater Pump — Impeller Failure',
    description: 'Starboard Caterpillar C18 seawater cooling pump impeller found heavily corroded and partially disintegrated. Pump shows cavitation damage to housing. Immediate replacement required to prevent engine overheating.',
    location_on_vessel: 'Engine Room — Starboard Side, Frame 32',
    severity: 'HIGH',
    status: 'PENDING_APPROVAL',
    root_cause: 'CORROSION',
    disposition: 'REPLACE',
    is_class_defect: true,
    class_item_ref: 'RINA-ME-002',
    discovered_by: 'Nadir',
    discovered_date: '2026-04-23',
    closed_date: null,
    cost_impact: 8500,
    schedule_impact_days: 3,
    change_order_id: 'co-001',
    created_at: '2026-04-23T09:15:00Z',
  },
  {
    id: 'defect-002',
    project_id: 'project-001',
    inspection_event_id: 'insp-003',
    work_package_id: 'wp-005',
    ncr_number: 'NCR-2026-002',
    title: 'Forestay Lower Terminal — Fatigue Cracking',
    description: 'Forestay lower swaged terminal shows circumferential fatigue cracking at the swage/wire interface. Cracking visible to naked eye. Structural integrity compromised. Must be replaced before mast re-step.',
    location_on_vessel: 'Foredeck — Forestay chainplate, Frame 2',
    severity: 'CRITICAL',
    status: 'OPEN',
    root_cause: 'FATIGUE',
    disposition: 'REPLACE',
    is_class_defect: false,
    class_item_ref: null,
    discovered_by: 'Tom Bradley',
    discovered_date: '2026-04-29',
    closed_date: null,
    cost_impact: null,
    schedule_impact_days: null,
    change_order_id: null,
    created_at: '2026-04-29T14:30:00Z',
  },
]

// ─── Change Orders ────────────────────────────────────────────────────────────

export const MOCK_CHANGE_ORDERS: ChangeOrder[] = [
  {
    id: 'co-001',
    project_id: 'project-001',
    co_number: 'CO-2026-001',
    title: 'Starboard Engine Seawater Pump Replacement',
    description: 'Replacement of starboard C18 seawater cooling pump due to impeller failure and cavitation damage discovered during pre-service inspection (NCR-2026-001). Includes new Caterpillar OEM pump unit, installation labour, and pressure testing.',
    trigger_type: 'DEFECT_DISCOVERY',
    status: 'PENDING_APPROVAL',
    cost_delta: 8500,
    schedule_delta_days: 3,
    raised_by: 'Nadir',
    raised_date: '2026-04-23',
    defect_record_id: 'defect-001',
    approval_id: 'appr-001',
    created_at: '2026-04-23T11:00:00Z',
  },
]

// ─── Owner Approvals ──────────────────────────────────────────────────────────

export const MOCK_APPROVALS: OwnerApproval[] = [
  {
    id: 'appr-001',
    project_id: 'project-001',
    approval_number: 'APPR-2026-001',
    title: 'Approve CO-2026-001: Starboard Engine Seawater Pump Replacement',
    description: 'Owner approval required for change order CO-2026-001. Cost impact €8,500 above baseline. Schedule impact +3 days. Classified as Tier 1 approval (under €10,000).',
    tier: 'TIER_1',
    status: 'PENDING',
    requested_by: 'Nadir',
    requested_date: '2026-04-23',
    approver_name: null,
    decision_date: null,
    decision_notes: null,
    change_order_id: 'co-001',
    cost_amount: 8500,
    deadline: '2026-04-30',
    created_at: '2026-04-23T11:30:00Z',
  },
]

// ─── Documents ────────────────────────────────────────────────────────────────

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'doc-001',
    project_id: 'project-001',
    doc_number: 'DOC-2026-001',
    title: 'RINA Class Certificate — Current',
    doc_type: 'CLASS_CERTIFICATE',
    revision: 'Rev.0',
    status: 'APPROVED',
    file_url: null,
    file_size: 245760,
    mime_type: 'application/pdf',
    uploaded_by: 'Nadir',
    uploaded_date: '2026-01-20',
    linked_object_type: 'PROJECT',
    linked_object_id: 'project-001',
    is_class_document: true,
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'doc-002',
    project_id: 'project-001',
    doc_number: 'DOC-2026-002',
    title: 'Project ZERO — 5YS Specification Package',
    doc_type: 'SPECIFICATION',
    revision: 'Rev.2',
    status: 'APPROVED',
    file_url: null,
    file_size: 1572864,
    mime_type: 'application/pdf',
    uploaded_by: 'Nadir',
    uploaded_date: '2026-02-10',
    linked_object_type: 'PROJECT',
    linked_object_id: 'project-001',
    is_class_document: false,
    created_at: '2026-02-10T09:00:00Z',
  },
  {
    id: 'doc-003',
    project_id: 'project-001',
    doc_number: 'DOC-2026-003',
    title: 'NCR-2026-001 Photographic Evidence',
    doc_type: 'PHOTO',
    revision: 'Rev.0',
    status: 'APPROVED',
    file_url: null,
    file_size: 8388608,
    mime_type: 'image/jpeg',
    uploaded_by: 'Nadir',
    uploaded_date: '2026-04-23',
    linked_object_type: 'DEFECT_RECORD',
    linked_object_id: 'defect-001',
    is_class_document: false,
    created_at: '2026-04-23T09:45:00Z',
  },
  {
    id: 'doc-004',
    project_id: 'project-001',
    doc_number: 'DOC-2026-004',
    title: 'CO-2026-001 Cost Breakdown',
    doc_type: 'CHANGE_ORDER',
    revision: 'Rev.0',
    status: 'UNDER_REVIEW',
    file_url: null,
    file_size: 102400,
    mime_type: 'application/pdf',
    uploaded_by: 'Nadir',
    uploaded_date: '2026-04-23',
    linked_object_type: 'CHANGE_ORDER',
    linked_object_id: 'co-001',
    is_class_document: false,
    created_at: '2026-04-23T11:15:00Z',
  },
  {
    id: 'doc-005',
    project_id: 'project-001',
    doc_number: 'DOC-2026-005',
    title: 'Pendennis Shipyard — Master Works Agreement',
    doc_type: 'CORRESPONDENCE',
    revision: 'Rev.1',
    status: 'APPROVED',
    file_url: null,
    file_size: 512000,
    mime_type: 'application/pdf',
    uploaded_by: 'Nadir',
    uploaded_date: '2026-01-15',
    linked_object_type: 'PROJECT',
    linked_object_id: 'project-001',
    is_class_document: false,
    created_at: '2026-01-15T14:00:00Z',
  },
]

// ─── Project Members ──────────────────────────────────────────────────────────

export const MOCK_MEMBERS: ProjectMember[] = [
  {
    id: 'user-001',
    project_id: 'project-001',
    user_id: 'user-001',
    role: 'OWNERS_REP',
    name: 'Nadir',
    email: 'nadir@yam.limited',
    company: 'YAM.Limited',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'user-002',
    project_id: 'project-001',
    user_id: 'user-002',
    role: 'OWNER',
    name: 'Alexander Fontaine',
    email: 'alex@fontaine-family.com',
    company: 'Fontaine Family Office',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'user-003',
    project_id: 'project-001',
    user_id: 'user-003',
    role: 'CAPTAIN',
    name: 'Captain James Harlow',
    email: 'captain@projectzero.com',
    company: null,
    created_at: '2026-01-15T00:00:00Z',
  },
]

// ─── World Model Events ───────────────────────────────────────────────────────

export const MOCK_EVENTS: WorldModelEvent[] = [
  {
    id: 'evt-001',
    project_id: 'project-001',
    event_type: 'DEFECT_CREATED',
    object_type: 'DEFECT_RECORD',
    object_id: 'defect-001',
    before_state: null,
    after_state: { ncr_number: 'NCR-2026-001', severity: 'HIGH', status: 'OPEN' },
    triggered_by: 'user-001',
    triggered_at: '2026-04-23T09:15:00Z',
    cascade_from_event_id: null,
  },
  {
    id: 'evt-002',
    project_id: 'project-001',
    event_type: 'CHANGE_ORDER_CREATED',
    object_type: 'CHANGE_ORDER',
    object_id: 'co-001',
    before_state: null,
    after_state: { co_number: 'CO-2026-001', cost_delta: 8500, status: 'PENDING_APPROVAL' },
    triggered_by: 'user-001',
    triggered_at: '2026-04-23T11:00:00Z',
    cascade_from_event_id: 'evt-001',
  },
  {
    id: 'evt-003',
    project_id: 'project-001',
    event_type: 'APPROVAL_CREATED',
    object_type: 'OWNER_APPROVAL',
    object_id: 'appr-001',
    before_state: null,
    after_state: { approval_number: 'APPR-2026-001', tier: 'TIER_1', status: 'PENDING' },
    triggered_by: 'user-001',
    triggered_at: '2026-04-23T11:30:00Z',
    cascade_from_event_id: 'evt-002',
  },
  {
    id: 'evt-004',
    project_id: 'project-001',
    event_type: 'DEFECT_CREATED',
    object_type: 'DEFECT_RECORD',
    object_id: 'defect-002',
    before_state: null,
    after_state: { ncr_number: 'NCR-2026-002', severity: 'CRITICAL', status: 'OPEN' },
    triggered_by: 'user-003',
    triggered_at: '2026-04-29T14:30:00Z',
    cascade_from_event_id: null,
  },
  {
    id: 'evt-005',
    project_id: 'project-001',
    event_type: 'DOCUMENT_UPLOADED',
    object_type: 'DOCUMENT',
    object_id: 'doc-003',
    before_state: null,
    after_state: { doc_number: 'DOC-2026-003', title: 'NCR-2026-001 Photographic Evidence' },
    triggered_by: 'user-001',
    triggered_at: '2026-04-23T09:45:00Z',
    cascade_from_event_id: null,
  },
]

// ─── Auth User ────────────────────────────────────────────────────────────────

export const MOCK_AUTH_USER: AuthUser = {
  id: 'user-001',
  email: 'nadir@yam.limited',
  name: 'Nadir',
  role: 'OWNERS_REP',
}
